--1
SELECT NOME, ANO FROM FILMES;
--2
SELECT NOME, ANO FROM FILMES ORDER BY Ano;
--3
SELECT NOME, ANO, Duracao FROM FILMES WHERE Nome = 'de volta para o futuro';
--4
SELECT NOME, ANO, DURACAO FROM FILMES WHERE ANO = 1997;
--5
SELECT NOME, ANO, DURACAO FROM FILMES WHERE ANO > 2000;
--6
SELECT NOME, ANO, DURACAO FROM FILMES 
WHERE DURACAO > 100 AND DURACAO < 150 
ORDER BY DURACAO;
--7
SELECT ANO, COUNT(ANO) AS Quantidade 
FROM FILMES
GROUP BY ANO 
ORDER BY Quantidade DESC;
--8
SELECT ID, PrimeiroNome, UltimoNome, Genero
FROM ATORES
WHERE Genero = 'M';
--9
SELECT ID, PrimeiroNome, UltimoNome, Genero
FROM ATORES
WHERE Genero = 'F'
ORDER BY PrimeiroNome;
--10
SELECT F.NOME, G.GENERO
FROM FILMES F 
INNER JOIN FILMESGENERO FG ON F.ID = FG.IdFilme
INNER JOIN GENEROS G ON FG.IdGenero = G.Id;
--11
SELECT F.NOME, G.GENERO
FROM FILMES F 
INNER JOIN FILMESGENERO FG ON F.ID = FG.IdFilme
INNER JOIN GENEROS G ON FG.IdGenero = G.Id
WHERE G.GENERO = 'Mistério';
--12
SELECT F.Nome, A.PrimeiroNome, A.UltimoNome, EF.Papel
FROM FILMES F
INNER JOIN ELENCOFILME EF ON F.ID = EF.ID
INNER JOIN ATORES A ON EF.ID = A.ID;